# generated by genlibbuild

cc_library(
    name = 'cppwee',
    srcs = [
        'src/Engine.cpp',
        'src/IfStmt.cpp',
        'src/Merger.cpp',
        'src/Pipeline.cpp',
        'src/RunInstance.cpp',
        'src/Spliter.cpp',
        'src/StmtChunk.cpp',
        'src/Stmt.cpp',
        'src/StmtFactory.cpp',
    ]
)
cc_binary(
    name = 'cppwee_test',
    srcs = [
        'test/test.cpp',
    ],
    deps = [
        ":cppwee"
    ],
)
